'on':
  workflow_call:
    inputs:
      name:
        type: string
        required: true
    secrets:
      my_secret:
        required: true
jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Print input and secret
        run: |
          echo "Hello, ${{ inputs.name }}!"
          echo "The secret is ${{ secrets.my_secret }}."
