name: Reusable Workflow

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
    secrets:
      my_secret:
        required: true

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print input and secret
        run: |
          echo "Hello, ${{ inputs.name }}!"
          echo "The secret is ${{ secrets.my_secret }}."
