name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - 'dev'
          - 'test'
          - 'stage'
          - 'prod'
        default: 'test'
      region:
        description: 'Region'
        required: true
        type: choice
        options:
          - 'eastus'
          - 'westus'
        default: 'eastus'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Region: ${{ github.event.inputs.region }}"
      - name: List files in the directory
        run: ls -R
        
      - name: Setup - Fetch ${{ github.event.inputs.environment }} Configs
        id: config-env
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "config-terraform.json"
          prop_path: ${{ github.event.inputs.environment }}   
      
      - name: Setup - Variables
        id: variables
        run: |
          if [[ "${{ github.event.inputs.region }}" == "eastus" ]]; then
            echo "rg=${{ steps.config-env.outputs.RG_EASTUS }}" >> $GITHUB_OUTPUT
            echo "lap=${{ steps.config-env.outputs.LAP_EASTUS }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.region }}" == "westus" ]]; then
            echo "rg=${{ steps.config-env.outputs.RG_WESTUS }}" >> $GITHUB_OUTPUT
            echo "lap=${{ steps.config-env.outputs.LAP_WESTUS }}" >> $GITHUB_OUTPUT
          fi

          if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
            echo "environmentApproval=Development Approve" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.environment }}" == "test" ]]; then
            echo "environmentApproval=Test Approve" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.environment }}" == "stage" ]]; then
            echo "environmentApproval=Stage Approve" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            echo "environmentApproval=Production Approve" >> $GITHUB_OUTPUT
          fi

          echo "scriptPath=${{ steps.config-env.outputs.SCRIPTS_PATH }}" >> $GITHUB_OUTPUT

      - name: Print - Variables
        run: |
          echo "rg: ${{ steps.variables.outputs.rg }}"
          echo "lap: ${{ steps.variables.outputs.lap }}"
          echo "Env: ${{ steps.variables.outputs.environmentApproval }}"
          echo "scriptPath: ${{ steps.variables.outputs.scriptPath }}"
          echo "Inputs: ${{ toJSON(github.event.inputs) }}"
